# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: oncall
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZTU1ODdiOTgyYzc0ZDEyNjMzMGVkMWJkMjc2YTI3ZmYxNTU5MjAzNWExYzQzNTUwY2VmYzNmOWE1MzlhZjBlM2FhZDI5MjA0NTM5NjY3MTMyMmUwMTFmOWQzODgxMjE4ZDAyNGMxZTc0OWQ4MWEzOWYwY2Q5OGU2ZWYxOWUxNjg=
